// generated by IOST.DevTools last: 3/25/2019 9:28:04 PM
namespace IOSTSdk.Contract.Economic
{
     using IOSTSdk;

    /// <summary>
    /// RAM related contract, including buying/selling/transferring.
    /// Details of economic model are introduced on RAM economic model.
    /// Buying/Selling RAM not too much, you can get price estimate in RPC.
    /// 
    /// Version: javascript
    /// Language: 1.0.0
    /// Reference: https://developers.iost.io/docs/en/6-reference/EconContract.html
    /// </summary>
    public static class Ram
    {
        public const string Cid = "ram.iost";

        /// <summary>
        /// buy RAM from system. minimum buying amount is 10 bytes.
        /// contract will return IOST costed.
        /// </summary>
        /// <param name="arg0">who buys ram. Permission of this account is needed.</param>
        /// <param name="arg1">who gets the bought ram</param>
        /// <param name="arg2">RAM byte to buy</param>
        public static Transaction RamBuy(this Transaction tx, string arg0, string arg1, int arg2)
        {
            tx.AddAction(Cid, "buy", arg0, arg1, arg2);
            return tx;
        }

        /// <summary>
        /// Sell unused RAM to system. minimum selling amount is 10 bytes.
        /// contract will return IOST returned.
        /// </summary>
        /// <param name="arg0">who sells RAM. Permission of this account is needed.</param>
        /// <param name="arg1">who gets IOST returned</param>
        /// <param name="arg2">RAM byte to sell</param>
        public static Transaction RamSell(this Transaction tx, string arg0, string arg1, int arg2)
        {
            tx.AddAction(Cid, "sell", arg0, arg1, arg2);
            return tx;
        }

        /// <summary>
        /// transfer RAM to others.
        /// Only RAM one bought can be transferred to others. So RAM others transferred to you cannot be sold to system nor transferred to others.
        /// minimum transferring amount is 10 bytes.
        /// </summary>
        /// <param name="arg0">who transfers RAM. Permission of this account is needed.</param>
        /// <param name="arg1">who gets transferred RAM</param>
        /// <param name="arg2">RAM byte to transfer</param>
        public static Transaction RamLend(this Transaction tx, string arg0, string arg1, int arg2)
        {
            tx.AddAction(Cid, "lend", arg0, arg1, arg2);
            return tx;
        }
    }
}
