// generated by IOST.DevTools last: 3/26/2019 5:52:40 AM
namespace IOSTSdk.Contract.System
{
     using IOSTSdk;

    /// <summary>
    /// Formal node? Building block reward? Management
    /// 
    /// Version: javascript
    /// Language: 1.0.0
    /// Reference: https://developers.iost.io/docs/en/6-reference/SystemContract.html
    /// </summary>
    public static class Bonus
    {
        public static readonly string Cid = "bonus.iost";

        /// <summary>
        /// The contribution value is issued and the system automatically calls
        /// </summary>
        /// <param name="data"></param>
        public static Transaction BonusIssueContribute(this Transaction tx, object data)
        {
            tx.AddAction(Cid, "issueContribute", data);
            return tx;
        }

        /// <summary>
        /// Use the contribution value to redeem IOST
        /// </summary>
        /// <param name="accountName"></param>
        /// <param name="quantity"></param>
        public static Transaction BonusExchangeIOST(this Transaction tx, string accountName, string quantity)
        {
            tx.AddAction(Cid, "exchangeIOST", accountName, quantity);
            return tx;
        }
    }
}
