// generated by IOST.DevTools last: 3/21/2019 12:22:56 PM
namespace IOSTSdk.Contract.System
{
    /// <summary>
    /// Formal node? Building block reward? Management
    /// 
    /// Version: javascript
    /// Language: 1.0.0
    /// Reference: https://developers.iost.io/docs/en/6-reference/SystemContract.html
    /// </summary>
    public partial class Bonus : Contract
    {
        private const string Cid = "bonus.iost";

        /// <summary>
        /// The contribution value is issued and the system automatically calls
        /// </summary>
        /// <param name="data"></param>
        public static void IssueContribute(Transaction tx, object data)
        {
            tx.AddAction(Cid, "issueContribute", data);
        }

        /// <summary>
        /// Use the contribution value to redeem IOST
        /// </summary>
        /// <param name="accountName"></param>
        /// <param name="quantity"></param>
        public static void ExchangeIOST(Transaction tx, string accountName, string quantity)
        {
            tx.AddAction(Cid, "exchangeIOST", accountName, quantity);
        }
    }
}
