// generated by IOST.DevTools last: 3/25/2019 6:12:55 AM
namespace IOSTSdk.Contract.System
{
     using IOSTSdk;

    /// <summary>
    /// Mainly used to sign up an account and transfer to this account, also can be used to transfer to an existing account.
    /// 
    /// Version: javascript
    /// Language: 1.0.0
    /// Reference: https://developers.iost.io/docs/en/6-reference/SystemContract.html
    /// </summary>
    public static class Exchange
    {
        public const string Cid = "exchange.iost";

        /// <summary>
        /// create account and transfer
        /// </summary>
        /// <param name="tokenSym">Token Identifier</param>
        /// <param name="to">Token receiving account, set to empty if create account</param>
        /// <param name="amount">Transfer amount</param>
        /// <param name="memo">Additional Information, set to create:{UserName}:{OwnerPublicKey}:{ActivePublicKey} if create account</param>
        public static Transaction ExchangeTransfer(this Transaction tx, string tokenSym, string to, string amount, string memo)
        {
            tx.AddAction(Cid, "transfer", tokenSym, to, amount, memo);
            return tx;
        }
    }
}
