namespace IOST.Contract.System
{
    /// <summary>
    /// https://developers.iost.io/docs/en/6-reference/SystemContract.html#systemiost
    /// </summary>
    public class System : Contract
    {
        private const string CID = "system.iost";

        /// <summary>
        /// Deploy smart contracts.
        /// 
        /// The smart contract code includes code and smart contract information, such as language and interface definitions. The code parameter supports two formats: json format and protobuf serialization encoding format. For developers, deployment contracts generally do not need to call this interface directly. It is recommended to use iwallet or related language SDK implementation.
        ///
        /// When deploying a smart contract, the system automatically calls the init() function of the smart contract.The developer can do some initialization work in the init function.
        ///
        /// Return value contractID is the smart contract ID, which is globally unique and generated by the hash of the deployment contract transaction.The contractID starts with "Contract" and consists of uppercase and lowercase letters and numbers.Only one smart contract can be deployed in a transaction.
        /// </summary>
        /// <param name="tx"></param>
        /// <param name="code">Smart Contract Code</param>
        public static void SetCode(Transaction tx, string code)
        {
            tx.AddAction(CID, "setCode", code);
        }

        /// <summary>
        /// Upgrade smart contracts.
        /// 
        /// Upgrade the smart contract, code is the smart contract code, the format is the same as the parameter in SetCode.
        ///
        /// When upgrading a smart contract, the system will automatically check the upgrade permission, that is, the can_update(data) function in the contract, and the parameter data is the second parameter in the UpdateCode, if and only if the can_update function exists and the call returns true. The contract upgrade will succeed, otherwise the upgrade will fail and it is determined that there is no upgrade permission.
        /// </summary>
        /// <param name="tx"></param>
        /// <param name="code">Smart Contract Code</param>
        /// <param name="data">upgrade function parameters</param>
        public static void UpdateCode(Transaction tx, string code, string data)
        {
            tx.AddAction(CID, "updateCode", code, data);
        }

        /// <summary>
        /// Cancel a delayed transaction, call this function before the execution of the delayed transaction to cancel the delayed transaction.
        /// </summary>
        /// <param name="tx">Transaction hash</param>
        /// <param name="txHash"></param>
        public static void CancelDelaytx(Transaction tx, string txHash)
        {
            tx.AddAction(CID, "cancelDelaytx", txHash);
        }

        /// <summary>
        /// Check if the transaction has the permission of the account.
        /// </summary>
        /// <param name="tx"></param>
        /// <param name="acc">account name</param>
        /// <param name="permission">permission name</param>
        public static void RequireAuth(Transaction tx, string acc, string permission)
        {
            tx.AddAction(CID, "requireAuth", acc, permission);
        }

        /// <summary>
        /// Generate a transaction receipt, the receipt is stored in the block, and can also be queried through the transaction hash.
        /// </summary>
        /// <param name="tx"></param>
        /// <param name="data">receipt content</param>
        public static void Receipt(Transaction tx, string data)
        {
            tx.AddAction(CID, "receipt", data);
        }
    }
}
