// generated by IOST.DevTools last: 3/21/2019 12:22:56 PM
namespace IOST.Contract.System
{
    /// <summary>
    /// Base system contract for issuing and updating contracts and other basic system functions.
    /// 
    /// Version: native
    /// Language: 1.0.0
    /// Reference: https://developers.iost.io/docs/en/6-reference/SystemContract.html
    /// </summary>
    public partial class System : Contract
    {
        private const string Cid = "system.iost";

        /// <summary>
        /// Deploy smart contracts.
        /// </summary>
        /// <param name="code">Smart Contract Code</param>
        public static void SetCode(Transaction tx, string code)
        {
            tx.AddAction(Cid, "setCode", code);
        }

        /// <summary>
        /// Upgrade smart contracts.
        /// </summary>
        /// <param name="code">Smart Contract Code</param>
        /// <param name="data">upgrade function parameters</param>
        public static void UpdateCode(Transaction tx, string code, string data)
        {
            tx.AddAction(Cid, "updateCode", code, data);
        }

        /// <summary>
        /// Cancel a delayed transaction, call this function before the execution of the delayed transaction to cancel the delayed transaction.
        /// </summary>
        /// <param name="txHash">Transaction hash</param>
        public static void CancelDelaytx(Transaction tx, string txHash)
        {
            tx.AddAction(Cid, "cancelDelaytx", txHash);
        }

        /// <summary>
        /// Check if the transaction has the permission of the account.
        /// </summary>
        /// <param name="acc">account name</param>
        /// <param name="permission">permission name</param>
        public static void RequireAuth(Transaction tx, string acc, string permission)
        {
            tx.AddAction(Cid, "requireAuth", acc, permission);
        }

        /// <summary>
        /// Generate a transaction receipt, the receipt is stored in the block, and can also be queried through the transaction hash.
        /// </summary>
        /// <param name="data">receipt content</param>
        public static void Receipt(Transaction tx, string data)
        {
            tx.AddAction(Cid, "receipt", data);
        }
    }
}
