// generated by IOST.DevTools last: 3/25/2019 9:28:18 PM
namespace IOSTSdk.Contract.System
{
     using IOSTSdk;

    /// <summary>
    /// The Super Node campaigns for voting.
    /// 
    /// Version: javascript
    /// Language: 1.0.0
    /// Reference: https://developers.iost.io/docs/en/6-reference/SystemContract.html
    /// </summary>
    public static class VoteProducer
    {
        public const string Cid = "vote_producer.iost";

        /// <summary>
        /// Apply for registration to become a super node candidate.
        /// </summary>
        /// <param name="accountName"></param>
        /// <param name="publicKeyBase58Encoding"></param>
        /// <param name="location"></param>
        /// <param name="websiteUrl"></param>
        /// <param name="networkId"></param>
        /// <param name="isProducer"></param>
        public static Transaction Vote_producerApplyRegister(this Transaction tx, string accountName, string publicKeyBase58Encoding, string location, string websiteUrl, string networkId, bool isProducer)
        {
            tx.AddAction(Cid, "applyRegister", accountName, publicKeyBase58Encoding, location, websiteUrl, networkId, isProducer);
            return tx;
        }

        /// <summary>
        /// Apply for cancellation.
        /// </summary>
        /// <param name="accountName"></param>
        public static Transaction Vote_producerApplyUnregister(this Transaction tx, string accountName)
        {
            tx.AddAction(Cid, "applyUnregister", accountName);
            return tx;
        }

        /// <summary>
        /// To cancel the registration, you need to call ApplyUnregister first. After the audit is passed, you can call this interface.
        /// </summary>
        /// <param name="accountName"></param>
        public static Transaction Vote_producerUnregister(this Transaction tx, string accountName)
        {
            tx.AddAction(Cid, "unregister", accountName);
            return tx;
        }

        /// <summary>
        /// Update registration information.
        /// </summary>
        /// <param name="accountName"></param>
        /// <param name="publicKeyBase58Encoding"></param>
        /// <param name="location"></param>
        /// <param name="websiteUrl"></param>
        /// <param name="networkId"></param>
        public static Transaction Vote_producerUpdateProducer(this Transaction tx, string accountName, string publicKeyBase58Encoding, string location, string websiteUrl, string networkId)
        {
            tx.AddAction(Cid, "updateProducer", accountName, publicKeyBase58Encoding, location, websiteUrl, networkId);
            return tx;
        }

        /// <summary>
        /// Go online, indicating that the node is currently available for service.
        /// </summary>
        /// <param name="accountName"></param>
        public static Transaction Vote_producerLogInProducer(this Transaction tx, string accountName)
        {
            tx.AddAction(Cid, "logInProducer", accountName);
            return tx;
        }

        /// <summary>
        /// Offline means that the node is currently unable to provide services.
        /// </summary>
        /// <param name="accountName"></param>
        public static Transaction Vote_producerLogOutProducer(this Transaction tx, string accountName)
        {
            tx.AddAction(Cid, "logOutProducer", accountName);
            return tx;
        }

        /// <summary>
        /// vote.
        /// </summary>
        /// <param name="voterAccountName"></param>
        /// <param name="candidateAccountName"></param>
        /// <param name="numberOfVotes"></param>
        public static Transaction Vote_producerVote(this Transaction tx, string voterAccountName, string candidateAccountName, string numberOfVotes)
        {
            tx.AddAction(Cid, "vote", voterAccountName, candidateAccountName, numberOfVotes);
            return tx;
        }

        /// <summary>
        /// Cancel the vote.
        /// </summary>
        /// <param name="voterAccountName"></param>
        /// <param name="candidateAccountName"></param>
        /// <param name="numberOfVotes"></param>
        public static Transaction Vote_producerUnvote(this Transaction tx, string voterAccountName, string candidateAccountName, string numberOfVotes)
        {
            tx.AddAction(Cid, "unvote", voterAccountName, candidateAccountName, numberOfVotes);
            return tx;
        }

        /// <summary>
        /// Voters receive bonus awards.
        /// </summary>
        /// <param name="voterAccountName"></param>
        public static Transaction Vote_producerVoterWithdraw(this Transaction tx, string voterAccountName)
        {
            tx.AddAction(Cid, "voterWithdraw", voterAccountName);
            return tx;
        }

        /// <summary>
        /// The contestant receives a bonus award.
        /// </summary>
        /// <param name="candidateAccountName"></param>
        public static Transaction Vote_producerCandidateWithdraw(this Transaction tx, string candidateAccountName)
        {
            tx.AddAction(Cid, "candidateWithdraw", candidateAccountName);
            return tx;
        }

        /// <summary>
        /// Calculate voter's bonus awards.
        /// </summary>
        /// <param name="voterAccountName"></param>
        public static Transaction Vote_producerGetVoterBonus(this Transaction tx, string voterAccountName)
        {
            tx.AddAction(Cid, "getVoterBonus", voterAccountName);
            return tx;
        }

        /// <summary>
        /// Calculate contestant's bonus award.
        /// </summary>
        /// <param name="candidateAccountName"></param>
        public static Transaction Vote_producerGetCandidateBonus(this Transaction tx, string candidateAccountName)
        {
            tx.AddAction(Cid, "getCandidateBonus", candidateAccountName);
            return tx;
        }

        /// <summary>
        /// recharge iost to candidates' bonus pool.
        /// </summary>
        /// <param name="amount"></param>
        /// <param name="payerAccountName"></param>
        public static Transaction Vote_producerTopupCandidateBonus(this Transaction tx, string amount, string payerAccountName)
        {
            tx.AddAction(Cid, "topupCandidateBonus", amount, payerAccountName);
            return tx;
        }

        /// <summary>
        /// recharge iost to voters' bonus pool.
        /// </summary>
        /// <param name="candidateAccountName"></param>
        /// <param name="amount"></param>
        /// <param name="payerAccountName"></param>
        public static Transaction Vote_producerTopupVoterBonus(this Transaction tx, string candidateAccountName, string amount, string payerAccountName)
        {
            tx.AddAction(Cid, "topupVoterBonus", candidateAccountName, amount, payerAccountName);
            return tx;
        }
    }
}
