// generated by IOST.DevTools last: 3/21/2019 12:22:56 PM
namespace IOST.Contract.System
{
    /// <summary>
    /// The Super Node campaigns for voting.
    /// 
    /// Version: javascript
    /// Language: 1.0.0
    /// Reference: https://developers.iost.io/docs/en/6-reference/SystemContract.html
    /// </summary>
    public partial class VoteProducer : Contract
    {
        private const string Cid = "vote_producer.iost";

        /// <summary>
        /// Apply for registration to become a super node candidate.
        /// </summary>
        /// <param name="accountName"></param>
        /// <param name="publicKeyBase58Encoding"></param>
        /// <param name="location"></param>
        /// <param name="websiteUrl"></param>
        /// <param name="networkId"></param>
        /// <param name="isProducer"></param>
        public static void ApplyRegister(Transaction tx, string accountName, string publicKeyBase58Encoding, string location, string websiteUrl, string networkId, bool isProducer)
        {
            tx.AddAction(Cid, "applyRegister", accountName, publicKeyBase58Encoding, location, websiteUrl, networkId, isProducer);
        }

        /// <summary>
        /// Apply for cancellation.
        /// </summary>
        /// <param name="accountName"></param>
        public static void ApplyUnregister(Transaction tx, string accountName)
        {
            tx.AddAction(Cid, "applyUnregister", accountName);
        }

        /// <summary>
        /// To cancel the registration, you need to call ApplyUnregister first. After the audit is passed, you can call this interface.
        /// </summary>
        /// <param name="accountName"></param>
        public static void Unregister(Transaction tx, string accountName)
        {
            tx.AddAction(Cid, "unregister", accountName);
        }

        /// <summary>
        /// Update registration information.
        /// </summary>
        /// <param name="accountName"></param>
        /// <param name="publicKeyBase58Encoding"></param>
        /// <param name="location"></param>
        /// <param name="websiteUrl"></param>
        /// <param name="networkId"></param>
        public static void UpdateProducer(Transaction tx, string accountName, string publicKeyBase58Encoding, string location, string websiteUrl, string networkId)
        {
            tx.AddAction(Cid, "updateProducer", accountName, publicKeyBase58Encoding, location, websiteUrl, networkId);
        }

        /// <summary>
        /// Go online, indicating that the node is currently available for service.
        /// </summary>
        /// <param name="accountName"></param>
        public static void LogInProducer(Transaction tx, string accountName)
        {
            tx.AddAction(Cid, "logInProducer", accountName);
        }

        /// <summary>
        /// Offline means that the node is currently unable to provide services.
        /// </summary>
        /// <param name="accountName"></param>
        public static void LogOutProducer(Transaction tx, string accountName)
        {
            tx.AddAction(Cid, "logOutProducer", accountName);
        }

        /// <summary>
        /// vote.
        /// </summary>
        /// <param name="voterAccountName"></param>
        /// <param name="candidateAccountName"></param>
        /// <param name="numberOfVotes"></param>
        public static void Vote(Transaction tx, string voterAccountName, string candidateAccountName, string numberOfVotes)
        {
            tx.AddAction(Cid, "vote", voterAccountName, candidateAccountName, numberOfVotes);
        }

        /// <summary>
        /// Cancel the vote.
        /// </summary>
        /// <param name="voterAccountName"></param>
        /// <param name="candidateAccountName"></param>
        /// <param name="numberOfVotes"></param>
        public static void Unvote(Transaction tx, string voterAccountName, string candidateAccountName, string numberOfVotes)
        {
            tx.AddAction(Cid, "unvote", voterAccountName, candidateAccountName, numberOfVotes);
        }

        /// <summary>
        /// Voters receive bonus awards.
        /// </summary>
        /// <param name="voterAccountName"></param>
        public static void VoterWithdraw(Transaction tx, string voterAccountName)
        {
            tx.AddAction(Cid, "voterWithdraw", voterAccountName);
        }

        /// <summary>
        /// The contestant receives a bonus award.
        /// </summary>
        /// <param name="candidateAccountName"></param>
        public static void CandidateWithdraw(Transaction tx, string candidateAccountName)
        {
            tx.AddAction(Cid, "candidateWithdraw", candidateAccountName);
        }

        /// <summary>
        /// Calculate voter's bonus awards.
        /// </summary>
        /// <param name="voterAccountName"></param>
        public static void GetVoterBonus(Transaction tx, string voterAccountName)
        {
            tx.AddAction(Cid, "getVoterBonus", voterAccountName);
        }

        /// <summary>
        /// Calculate contestant's bonus award.
        /// </summary>
        /// <param name="candidateAccountName"></param>
        public static void GetCandidateBonus(Transaction tx, string candidateAccountName)
        {
            tx.AddAction(Cid, "getCandidateBonus", candidateAccountName);
        }

        /// <summary>
        /// recharge iost to candidates' bonus pool.
        /// </summary>
        /// <param name="amount"></param>
        /// <param name="payerAccountName"></param>
        public static void TopupCandidateBonus(Transaction tx, string amount, string payerAccountName)
        {
            tx.AddAction(Cid, "topupCandidateBonus", amount, payerAccountName);
        }

        /// <summary>
        /// recharge iost to voters' bonus pool.
        /// </summary>
        /// <param name="candidateAccountName"></param>
        /// <param name="amount"></param>
        /// <param name="payerAccountName"></param>
        public static void TopupVoterBonus(Transaction tx, string candidateAccountName, string amount, string payerAccountName)
        {
            tx.AddAction(Cid, "topupVoterBonus", candidateAccountName, amount, payerAccountName);
        }
    }
}
