// generated by IOST.DevTools last: 3/21/2019 12:23:02 PM
namespace IOST.Contract.Economic
{
    /// <summary>
    /// GAS related contract, including pledging IOST for gas, unpleding, transferring GAS.
    /// Details of economic model are introduced on GAS economic model。
    /// 
    /// Version: native
    /// Language: 1.0.0
    /// Reference: https://developers.iost.io/docs/en/6-reference/EconContract.html
    /// </summary>
    public partial class Gas : Contract
    {
        private const string Cid = "gas.iost";

        /// <summary>
        /// pledge IOST for GAS. minimum pledging amount is 1 IOST.
        /// </summary>
        /// <param name="arg0">who pledges IOST. Permission of this account is needed.</param>
        /// <param name="arg1">who gets GAS</param>
        /// <param name="arg2">IOST amount for pledging</param>
        public static void Pledge(Transaction tx, string arg0, string arg1, string arg2)
        {
            tx.AddAction(Cid, "pledge", arg0, arg1, arg2);
        }

        /// <summary>
        /// undo pledge. IOST pledged earlier will be returned. minimum unpledging amount is 1 IOST.
        /// </summary>
        /// <param name="arg0">who unpledge IOST. Permission of this account is needed.</param>
        /// <param name="arg1">unpledge IOST out of who's current pledgement</param>
        /// <param name="arg2">IOST amount for unpledging</param>
        public static void Unpledge(Transaction tx, string arg0, string arg1, string arg2)
        {
            tx.AddAction(Cid, "unpledge", arg0, arg1, arg2);
        }

        /// <summary>
        /// transfer GAS. minimum transferring amount is 1 IOST.
        /// Notice: GAS obtained from pledgement cannot be transferred. Only transferable GAS can be transferred. Besides, transferable GAS after being transferred once will not be transferable any longer.
        /// You can obtain transferable GAS from transferable gas reward
        /// </summary>
        /// <param name="arg0">who transfers GAS. Permission of this account is needed.</param>
        /// <param name="arg1">who gets GAS</param>
        /// <param name="arg2">IOST amount for transferring</param>
        public static void Transfer(Transaction tx, string arg0, string arg1, string arg2)
        {
            tx.AddAction(Cid, "transfer", arg0, arg1, arg2);
        }
    }
}
